import duckdb
import pandas as pd
import joblib
import os
import numpy as np

DB_PATH = os.path.join(os.path.dirname(__file__), 'database', 'quant_data.duckdb')
MODEL_DIR = os.path.join(os.path.dirname(__file__), 'models', 'saved')
MAG_7 = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA"]

features_cols = [
    'return_1d', 'return_5d', 'rsi_14', 'sma_20_dist', 'sma_50_dist', 
    'volatility_20d', 'atr_percent', 'spy_sma_200', 'us_10y_yield', 'm2_money_supply'
]

def run_backtest():
    print("="*60)
    print("--- INITIATING HISTORICAL WALK-FORWARD BACKTEST ---")
    print("="*60)
    
    conn = duckdb.connect(DB_PATH)
    
    # Load all historical features
    df = conn.execute("SELECT * FROM features ORDER BY date ASC").df()
    conn.close()
    
    if df.empty:
        print("Error: No historical data found in the database.")
        return
        
    print(f"Loaded {len(df)} days of historical data.")
    
    trade_history = []
    
    for ticker in MAG_7:
        ticker_df = df[df['ticker'] == ticker].copy()
        if ticker_df.empty: continue
            
        model_path = os.path.join(MODEL_DIR, f"{ticker}_xgb.joblib")
        if not os.path.exists(model_path):
            print(f"Skipping {ticker}: No trained model found.")
            continue
            
        model = joblib.load(model_path)
        
        # Pre-calculate AI probabilities for speed
        X = ticker_df[features_cols].fillna(0)
        ticker_df['ai_prob'] = model.predict_proba(X)[:, 1]
        
        in_trade = False
        entry_price = 0
        take_profit = 0
        stop_loss = 0
        entry_date = None
        days_held = 0
        
        for idx, row in ticker_df.iterrows():
            date = row['date']
            close = row['close']
            atr = row['atr_percent']
            prob = row['ai_prob']
            macro_safe = row['spy_close'] > row['spy_sma_200']
            
            if not in_trade:
                # ENTRY LOGIC
                if macro_safe and prob > 0.55:
                    in_trade = True
                    entry_price = close
                    entry_date = date
                    take_profit = entry_price * (1 + (atr * 2.0))
                    stop_loss = entry_price * (1 - (atr * 1.0))
                    days_held = 0
            else:
                # IN TRADE LOGIC
                days_held += 1
                
                # Trailing Stop Loss
                new_theoretical_sl = close * (1 - (atr * 1.0))
                if new_theoretical_sl > stop_loss:
                    stop_loss = new_theoretical_sl
                
                # EXIT LOGIC
                exit_reason = None
                if close >= take_profit:
                    exit_reason = "TAKE_PROFIT"
                elif close <= stop_loss:
                    exit_reason = "STOP_LOSS"
                elif days_held >= 40:
                    exit_reason = "TIME_STOP"
                    
                if exit_reason:
                    profit_loss = close - entry_price
                    pl_percent = (profit_loss / entry_price) * 100
                    trade_history.append({
                        'Ticker': ticker,
                        'Entry Date': entry_date,
                        'Exit Date': date,
                        'Entry Price': entry_price,
                        'Exit Price': close,
                        'Return %': pl_percent,
                        'Exit Reason': exit_reason,
                        'Days Held': days_held
                    })
                    in_trade = False

    # Aggregate Results
    if not trade_history:
        print("\nNo trades were generated by the AI in the historical dataset.")
        return
        
    results_df = pd.DataFrame(trade_history)
    
    total_trades = len(results_df)
    winning_trades = len(results_df[results_df['Return %'] > 0])
    losing_trades = len(results_df[results_df['Return %'] <= 0])
    win_rate = (winning_trades / total_trades) * 100
    
    avg_win = results_df[results_df['Return %'] > 0]['Return %'].mean() if winning_trades > 0 else 0
    avg_loss = results_df[results_df['Return %'] <= 0]['Return %'].mean() if losing_trades > 0 else 0
    
    total_cumulative_return = results_df['Return %'].sum()
    
    print("\n" + "="*40)
    print("--- AI BACKTEST PERFORMANCE REPORT ---")
    print("="*40)
    print(f"Total Trades Executed: {total_trades}")
    print(f"Win Rate:              {win_rate:.1f}% ({winning_trades}W / {losing_trades}L)")
    print(f"Average Win:           +{avg_win:.2f}%")
    print(f"Average Loss:          {avg_loss:.2f}%")
    print(f"Gross Cumulative ROI:  +{total_cumulative_return:.2f}%")
    print("="*40)
    
    print("\nRecent Trades Breakdown:")
    recent_trades = results_df.tail(10)
    for _, trade in recent_trades.iterrows():
        status = "WIN " if trade['Return %'] > 0 else "LOSS"
        print(f"[{trade['Exit Date'].strftime('%Y-%m-%d')}] {ticker.ljust(5)} | {status} | Return: {trade['Return %']:+6.2f}% | Reason: {trade['Exit Reason']} | Days: {trade['Days Held']}")

if __name__ == "__main__":
    run_backtest()
